name: Run Tests

on: [push]

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
jobs:

  test:
    name: Run System Tests
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 13
          distribution: 'adopt'

      - name: Run All System Tests
        run: ./gradlew clean test --tests "SystemTest.*"


