name: Run Tests

on: [push]

jobs:
  test:
    name: Run System Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 13

      - name: Run All System Tests
        run: ./gradlew clean test --tests "SystemTest.*"
